version: "3.8"
services:
  xhs-downloader:
    image: xhs-downloader
    build:
      context: .
    volumes:
      - .:/app
    command: ["python", "main.py", "server"]
networks:
  default:
    external:
      name: yoosoul
