version: "3.8"
services:
  xhs-downloader:
    image: xhs-downloader
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "main.py", "server"]
networks:
  default:
    external:
      name: yoosoul
